---
- hosts: 172.31.34.159
  become: yes
  tasks:
  - name: i want to install git
    apt:
      name: git
      state: present
  - name: i want to install tree
    apt:
      name: tree
      state: present
  - name: install wget
    apt:
      name: wget
      state: present