---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to ping
    ping:
  - name: i want to install webserver on ubuntu ansible nodes
    apt:
      name: apache2
      state: present
    when: ansible_so_family =="Debian"
  - name: i want to install webserver on RedHat ansible nodes
    yum:
      name: httpd
      state: present
    when: ansible_so_family =="RedHat"