---
- name: create a new group
  group:
    name: tomcat
    state: present
- name: create a new user
  user:
    name: tomcat
    shell: /bin/false
    group: tomcat
    home: /opt/tomcat
    state: present