---
- name: Give the tomcat group ownership
  file:
    path: /opt/tomcat/conf
    group: tomcat
    state: directory
    recurse: yes
- name: give the tomcat group read access to the conf directory
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+r
    recurse: yes
- name: give the tomcat group execute access to the conf  directory
  file:
    path: /opt/tomcat/conf
    state: directory
    mode: g+x
- name: Make the tomcat user the owner of the webapps
  file:
    path: /opt/tomcat/webapps
    owner: tomcat
    state: directory
    recurse: yes
- name: Make the tomcat user the owner of the work
  file:
    path: /opt/tomcat/work
    owner: tomcat
    state: directory
    recurse: yes
- name: Make the tomcat user the owner of the temp
  file:
    path: /opt/tomcat/temp
    owner: tomcat
    state: directory
    recurse: yes
- name: Make the tomcat user the owner of the logs
  file:
    path: /opt/tomcat/logs
    owner: tomcat
    state: directory
    recurse: yes